### ISSUE TITLE
Tried example from readme

### ISSUE THREAD

**Issue by NCrashed** [Indaxia/WLPM#1]
![image](https://user-images.githubusercontent.com/2116167/58981758-ace83f00-87db-11e9-9af1-ba961dd07c60.png)

Followed quick start instruction and got that.

Platform: Windows 10 x64_86
Version: 0.6.1-beta
WE Version: 1.31 (6072)

The map:
[LiC.w3x.zip](https://github.com/Indaxia/WLPM/files/3258613/LiC.w3x.zip)

**Comment by ScorpioT1000** [comment]
You forgot to add comma after "dependencies": {}

**Comment by ScorpioT1000** [comment]
Also your dependency must be inside curly braces in the "dependencies"  object instead.
Please refer json format docs: https://www.w3schools.com/js/js_json_syntax.asp

**Comment by NCrashed** [comment]
Hmm, the wlpm-package.json wasn't created by me. It was generated with `wlpm update` and then `wlpm install https://github.com/Indaxia/wlpm-wc3-demo-hello 1.1`. I ofc can fix it by hand, but the issue is about bug in project generation.

**Comment by ScorpioT1000** [comment]
Fixed in [0.7-beta](https://github.com/Indaxia/WLPM/tree/0.7-beta)
